version: '2.3'
services:
        icon:
                build:
                        context: ./
                image: frt/ear
                container_name: ear
                ports:
                        - 127.0.0.1:11120:8888
                volumes:  
                        - ./src:/mnt
                runtime: nvidia
                environment:
                        - NVIDIA_VISIBLE_DEVICES=all
                        - NVIDIA_DRIVER_CAPABILITIES=all
